# TeamStation AI — Documentation (custom domain)
title: "TeamStation AI Documentation"
description: "CTO-grade docs for Axiom Cortex™ (Cognitive AI evaluation) and the Nearshore IT Co-Pilot™ platform."

# Canonicals (MUST be set for absolute sitemap URLs)
url: "https://docs.teamstation.dev"
baseurl: ""   # root of subdomain

# Build
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

# GitHub Pages–safe plugins (sitemap required)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Pretty URLs
permalink: pretty

# Collections (so /_axiom_cortex/ pages build)
collections:
  axiom_cortex:
    output: true
    permalink: /axiom-cortex/:name/
  copilot:
    output: true
    permalink: /co-pilot/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "TeamStation AI"
  - scope:
      path: ""
      type: "axiom_cortex"
    values:
      layout: "page"
      author: "TeamStation AI"
      section: "axiom-cortex"
  - scope:
      path: ""
      type: "copilot"
    values:
      layout: "page"
      author: "TeamStation AI"
      section: "co-pilot"

# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
