# TeamStation AI — Documentation (custom domain)
title: "TeamStation AI Documentation"
description: "CTO-grade docs for Axiom Cortex™ (Cognitive AI evaluation) and the Nearshore IT Co-Pilot™ platform."

# Canonicals for docs subdomain
url: "https://docs.teamstation.dev"
baseurl: ""  # root of the subdomain

# Build
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

# GitHub Pages–safe plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Pretty URLs
permalink: pretty

# Sass (optional)
sass:
  sass_dir: _sass
  style: compressed

# ✅ Collections (this is what makes /_axiom_cortex/ build again)
collections:
  axiom_cortex:
    output: true
    permalink: /axiom-cortex/:name/
  copilot:
    output: true
    permalink: /co-pilot/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "TeamStation AI"
  - scope:
      path: ""
      type: "axiom_cortex"
    values:
      layout: "page"
      author: "TeamStation AI"
      section: "axiom-cortex"
  - scope:
      path: ""
      type: "copilot"
    values:
      layout: "page"
      author: "TeamStation AI"
      section: "co-pilot"

# SEO / social
seo:
  type: Organization
  name: TeamStation AI
  links:
    - https://teamstation.dev
    - https://github.com/TeamStation-AI
    - https://scholar.google.com/citations?user=aNol-ycAAAAJ

# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
