# TeamStation AI — Docs (GitHub Pages Project site)
# Live site: https://teamstation-ai.github.io/docs/

title: "TeamStation AI Documentation"
description: "CTO-grade docs for Axiom Cortex™ (Cognitive AI) and the Nearshore IT Co-Pilot™ platform."

# IMPORTANT: these two lines must match your Pages URL exactly
url: "https://teamstation-ai.github.io"
baseurl: "/docs"

markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: America/Mexico_City

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

# Publish Axiom Cortex & Co-Pilot sections
collections:
  axiom_cortex:
    output: true
    permalink: /axiom-cortex/:name/
  copilot:
    output: true
    permalink: /co-pilot/:name/

# Default front-matter
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author: "TeamStation AI"
  - scope:
      path: ""
      type: axiom_cortex
    values:
      layout: page
      author: "TeamStation AI"
      section: axiom-cortex
  - scope:
      path: ""
      type: copilot
    values:
      layout: page
      author: "TeamStation AI"
      section: co-pilot

# Used by jekyll-seo-tag
seo:
  type: Organization
  name: TeamStation AI
  links:
    - https://teamstation.dev
    - https://github.com/TeamStation-AI

social:
  type: Organization
  name: TeamStation AI
  links:
    - https://teamstation.dev
    - https://github.com/TeamStation-AI

include:
  - robots.txt
  - humans.txt

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
