# Jekyll Configuration for TeamStation AI Docs (GitHub Pages project site)

title: "TeamStation AI Documentation"
description: "CTO-grade documentation for Axiom Cortex™ (Cognitive AI evaluation) and the Nearshore IT Co-Pilot™ platform."

# IMPORTANT for GitHub Pages project sites:
url: "https://teamstation-ai.github.io"   # org/user site URL
baseurl: "/docs"                           # repo name prefixed with /

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM          # GitHub Flavored Markdown (makes links render reliably)
  hard_wrap: false
  auto_ids: true

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Collections (keep Axiom Cortex pages grouped)
collections:
  axiom_cortex:
    output: true
    permalink: /axiom-cortex/:name/
  copilot:
    output: true
    permalink: /co-pilot/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
      author: "TeamStation AI"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "TeamStation AI"
  - scope:
      path: ""
      type: "axiom_cortex"
    values:
      layout: "page"
      author: "TeamStation AI"
      section: "axiom-cortex"
  - scope:
      path: ""
      type: "copilot"
    values:
      layout: "page"
      author: "TeamStation AI"
      section: "co-pilot"

# SEO (jekyll-seo-tag uses this)
seo:
  type: Organization
  name: TeamStation AI
  links:
    - https://teamstation.dev
    - https://github.com/TeamStation-AI

# Social profile hints
social:
  type: Organization
  name: TeamStation AI
  links:
    - https://teamstation.dev
    - https://github.com/TeamStation-AI

# Permalinks
permalink: pretty

# Include/Exclude
include:
  - robots.txt
  - humans.txt
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
